#!/bin/bash

read -r -d '' USAGE <<'EOF'
Usage: build-rpm [-n project_name]
Example: build-rpm
Example: build-rpm -n mobnode-testbuild
EOF

NODE_PROJECT=mobnode
RELEASE=
PROJECT_DIR=

while getopts n: opt; do
  case $opt in
    n)
      NODE_PROJECT="$OPTARG"
      PROJECT_DIR="$NODE_PROJECT`date +%Y%m%d%H%M`"
      ;;
    \?)
      echo "${USAGE}" >&2
      exit 1
      ;;
    esac
done

NPM_ENV="client/.env.default"
if [ -e $NPM_ENV ]; then
  if ! grep -q REACT_APP_TAG $NPM_ENV; then
    echo "REACT_APP_TAG must be in $NPM_ENV" >&2
    exit 2
  fi
  RELEASE=`grep REACT_APP_TAG $NPM_ENV | awk -F "=" '{print $2}' | tr -d '"' | awk -F "-" '{print $2}'`
  if [ -z "$RELEASE" ]; then
    echo "Cannot determine release value from REACT_APP_TAG" >&2
    exit 3
  fi
else
  echo "$NPM_ENV must exist and contain REACT_APP_TAG" >&2
  exit 4
fi

mkdir -p {SOURCES,SPECS}
mkdir -p ~/rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}

speculate --release=${RELEASE} || exit 2

cp SPECS/${NODE_PROJECT}.spec ~/rpmbuild/SPECS/ || exit 2
cp SOURCES/${NODE_PROJECT}.tar.gz ~/rpmbuild/SOURCES/ || exit 2

pushd ~/rpmbuild/SPECS
rpmbuild -bb ${NODE_PROJECT}.spec || exit 2
popd
