#!/bin/bash

###############
# Attempts to retrieve the couchdb proxy "secret" value in order to configure
# MobNode to use it.
###############

if [ $# != 1 ]; then
  echo "Usage: mnaddsecret [config_file]"
  echo "Example: ./mnaddsecret client/.env"
  exit 1
fi

ENV_FILE="$1"

if [ -e /etc/couchdb/local.ini ]; then
  ENV_STR="COUCH_AUTH_SECRET"
  SEC=`grep "^[ ]*secret[ ]*=" /etc/couchdb/local.ini | tr -d '[:space:]' | awk -F "=" '{print $2}'`

  if [ -n "$SEC" ]; then
    if [ -e ${ENV_FILE} ]; then
      grep -v "${ENV_STR}" ${ENV_FILE} > ${ENV_FILE}.tmp
    fi
    echo "${ENV_STR}=\"${SEC}\"" >> ${ENV_FILE}.tmp
    mv ${ENV_FILE}.tmp ${ENV_FILE}
  fi
fi
  
